[package]
name = "hex_brains_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = {  version = "0.12.0", features = ["multi-threaded"] }
rayon = "1.8.0"
puffin = "0.17.0"
tinyrand = "0.5.0"
tracing = "0.1.40"

[dev-dependencies]
tinyrand = "0.5.0"
tinyrand-alloc = "0.5.0"
