[package]
name = "hex_brains_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = {  version = "0.12.0", features = ["multi-threaded"] }
rayon = "1.8.0"
puffin = "0.17.0"
rand = "0.8.5"
tracing = "0.1.40"
