[package]
name = "hex_brains_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
hex_brains_engine = { path = "../engine" }
bevy_ecs = "0.11.3"
eframe = { version = "0.23.0", features = ["puffin"] }
egui = "0.23.0"
puffin = "0.17.0"
puffin_http = "0.14.0"
puffin_egui = "0.23.0"
