# Trigger the workflow on pushes or PRs to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Permissions for pushing to GitHub Container Registry (ghcr.io)
permissions:
  contents: read
  packages: write

name: Continuous integration

jobs:
  # Job 1: Build a shared Docker image from .devcontainer/Dockerfile for consistent CI environment
  # This ensures reproducibility across build targets; image is loaded locally (no push to registry)
  setup:
    name: Build Shared Environment Image
    runs-on: ubuntu-latest  # Host VM only (provides Docker)
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4

      # Log in to GitHub Container Registry for pushing/pulling the custom image
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Always build and push custom image (pulls existing if available, rebuilds changed layers only)
      # Fast due to layer cache; unique tag ensures versioned reproducibility; fails loudly if Dockerfile issues
      - name: Build and Push Docker Image from Dockerfile
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/hex-brains-builder:${{ github.sha }}

      # Set output to the full tagged image for use in build job
      - name: Set image output
        id: set-image
        run: echo "image=ghcr.io/${{ github.repository }}/hex-brains-builder:${{ github.sha }}" >> $GITHUB_OUTPUT

  # Job 2: Build the Rust project using the shared Docker image via volume mount (avoids containerized actions)
  # Checkout and cache on host; run cargo build inside container with mounted workspace for consistency
  build:
    name: Build Project
    runs-on: ubuntu-latest  # Host VM with Docker; build runs via docker run
    needs: setup  # Depends on image build
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
#          - wasm32-unknown-unknown
          - x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Targets (for host cache setup)
        run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          workspaces: "engine -> target/${{ matrix.target }}/deps; gui -> target/${{ matrix.target }}/deps"
          prefix-key: "cargo-build-target-${{ matrix.target }}-${{ runner.os }}"
      - name: Log in to GHCR (for pulling the image)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Cargo in Container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ github.workspace }}/target/${{ matrix.target }}:/workspace/target/${{ matrix.target }} \
            -w /workspace \
            ${{ needs.setup.outputs.image }} \
            bash -c "rustup target add ${{ matrix.target }} && cargo build --workspace --release --target ${{ matrix.target }}"
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
      - name: Prepare Artifact
        run: mv target/${{ matrix.target }}/release/hex_brains_gui* .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hex-brains-${{ matrix.target }}
          path: |
            hex_brains_gui*
            !hex_brains_gui.d

  # Job 3: Send notification to Discord on build completion
  # Uses webhook secret; provides status, commit info, and artifact links
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build]  # notify job depends on check and build jobs
    steps:
      - name: Notify success on Discord
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SUCCESS }}
        with:
          args: |
            Build succeeded! :white_check_mark:
            Commit Message: "${{ github.event.head_commit.message }}"
            Artifacts: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
